services:
  nginx:
    container_name: nginx
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${HOME_DIR}/docker/configs/nginx/data:/data
      - ${HOME_DIR}/docker/configs/nginx/letsencrypt:/etc/letsencrypt
